INSERT OR IGNORE INTO communes (name, slug) VALUES
	("Alhué", "alhue"),
	("Buin", "buin"),
	("Calera de Tango", "calera-de-tango"),
	("Cerrillos", "cerrillos"),
	("Cerro Navia", "cerro-navia"),
	("Colina", "colina"),
	("Conchalí", "conchali"),
	("Curacaví", "curacavi"),
	("El Bosque", "el-bosque"),
	("El Monte", "el-monte"),
	("Estación Central", "estacion-central"),
	("Huechuraba", "huechuraba"),
	("Independencia", "independencia"),
	("Isla de Maipo", "isla-de-maipo"),
	("La Cisterna", "la-cisterna"),
	("La Florida", "la-florida"),
	("La Granja", "la-granja"),
	("La Pintana", "la-pintana"),
	("La Reina", "la-reina"),
	("Lampa", "lampa"),
	("Las Condes", "las-condes"),
	("Lo Barnechea", "lo-barnechea"),
	("Lo Espejo", "lo-espejo"),
	("Lo Prado", "lo-prado"),
	("Macul", "macul"),
	("Maipú", "maipu"),
	("María Pinto", "maria-pinto"),
	("Melipilla", "melipilla"),
	("Ñuñoa", "nunoa"),
	("Padre Hurtado", "padre-hurtado"),
	("Paine", "paine"),
	("Pedro Aguirre Cerda", "pedro-aguirre-cerda"),
	("Peñaflor", "penaflor"),
	("Peñalolén", "penalolen"),
	("Pirque", "pirque"),
	("Providencia", "providencia"),
	("Pudahuel", "pudahuel"),
	("Puente Alto", "puente-alto"),
	("Quilicura", "quilicura"),
	("Quinta Normal", "quinta-normal"),
	("Recoleta", "recoleta"),
	("Renca", "renca"),
	("San Bernardo", "san-bernardo"),
	("San Joaquín", "san-joaquin"),
	("San José de Maipo", "san-jose-de-maipo"),
	("San Miguel", "san-miguel"),
	("San Pedro", "san-pedro"),
	("San Ramón", "san-ramon"),
	("Santiago", "santiago"),
	("Talagante", "talagante"),
	("Tiltil", "tiltil"),
	("Vitacura", "vitacura");
